version: '3.7'

services:
  # Web Server - PHP + Nginx
  web:
    image: php:8.1-fpm
    container_name: gnuboard-web
    volumes:
      - ./web:/var/www/html
    networks:
      - gnuboard-network
    depends_on:
      - db
    restart: always

  # Nginx Server
  nginx:
    image: nginx:latest
    container_name: gnuboard-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/html
    ports:
      - "80:80"
    networks:
      - gnuboard-network
    depends_on:
      - web
    restart: always

  # Database - MySQL
  db:
    image: mysql:5.7
    container_name: gnuboard-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gnuboard-network
    restart: always

networks:
  gnuboard-network:
    driver: bridge

volumes:
  db_data:
